### ISSUE TITLE
code exception

### ISSUE THREAD

**Issue by dafik** [AntonMykolaienko/xml2json#1]
Exception in thread "main" java.lang.NumberFormatException
	at java.math.BigDecimal.parseExp(BigDecimal.java:638)
	at java.math.BigDecimal.<init>(BigDecimal.java:551)
	at java.math.BigDecimal.<init>(BigDecimal.java:383)
	at java.math.BigDecimal.<init>(BigDecimal.java:806)
	at de.odysseus.staxon.json.stream.util.AutoPrimitiveTarget.value(AutoPrimitiveTarget.java:54)
	at de.odysseus.staxon.json.JsonXMLStreamWriter.writeEndElementTag(JsonXMLStreamWriter.java:203)
	at de.odysseus.staxon.base.AbstractXMLStreamWriter.writeEndElement(AbstractXMLStreamWriter.java:217)
	at de.odysseus.staxon.event.SimpleXMLEventWriter.add(SimpleXMLEventWriter.java:60)
	at de.odysseus.staxon.util.EventWriterDelegate.add(EventWriterDelegate.java:60)
	at de.odysseus.staxon.json.util.XMLMultipleEventWriter.add(XMLMultipleEventWriter.java:90)
	at de.odysseus.staxon.json.util.XMLMultipleEventWriter.add(XMLMultipleEventWriter.java:75)
	at com.fs.xml2json.service.ConverterService.convert(ConverterService.java:106)
	at com.fs.xml2json.Starter.processFile(Starter.java:146)
	at com.fs.xml2json.Starter.noGuiHandler(Starter.java:117)
	at com.fs.xml2json.Starter.start(Starter.java:86)
	at com.fs.xml2json.Starter.main(Starter.java:62)
2017-11-21 13:07:54 INFO com.fs.xml2json.Starter:58: Shutting down application starter ...

**Comment by AntonMykolaienko** [comment]
@dafik Hi, do you have example of data, which you are trying to convert, this can be incorrect decimal part delimiter (comma instead of dot)

**Comment by AntonMykolaienko** [comment]
@dafik you have something like this:
<pre>
&lt;feature>
     &lt;command>command3&lt;/command>
     &lt;value>1e12345678912&lt;/value>
&lt;/feature>
</pre>

**Comment by dafik** [comment]
there is patch https://github.com/beckchr/staxon/issues/29

**Comment by AntonMykolaienko** [comment]
@dafik Added actual StAXON library (from master) as project's module, this will resolve problem with beg exponent values.
